spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery-mate?serverTimezone=Asia/Seoul
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
